### ISSUE TITLE
sign certificate requst 

### ISSUE THREAD

**Issue by UrielAbergel** [jcmoraisjr/simple-ca#5]
Hi
I'm trying to sign a certificate request from another computer I get either as a cer file or as a text file I would love to know how I can sign it and issue a signed certificate

Thanks so much for the help, a great project!

**Comment by jcmoraisjr** [comment]
Hi, in short you should create a certificate request and send it to the signer, the readme has some [usage samples](https://github.com/jcmoraisjr/simple-ca#usage), did you have any problem with some of them? What have you tried so far?

**Comment by UrielAbergel** [comment]
Hi,
I close this issue and I must say that repo is very helped me and is very recommended and it solves many of the problems that I have with other ca specifically with windows CAs.
the last question I have is how I can change the ca name with the build command

**Comment by jcmoraisjr** [comment]
>  the last question I have is how I can change the ca name with the build command

You cannot change the CA's common name once created. However in the first run, you can use `CA_CN` envvar to define a distinct common name - https://github.com/jcmoraisjr/simple-ca#options
